Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -13,16 +13,17 @@ build-and-push:
   variables:
     DOCKER_DRIVER: overlay2
   before_script:
-    - git config --global url."https://${CI_REPO_USER}:${CI_REPO_TOKEN}@gitlab.itsec.ur.de/".insteadOf "https://gitlab.itsec.ur.de/"
     - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
   script:
-    |
-    if [ -z "$VERSION" ]; then echo "ERROR: VERSION is required"; exit 1; fi
-    BASE_TAG="${BASE_TAG:-$DEFAULT_BASE_TAG}"
-    FULL_TAG="$BASE_TAG-$VERSION"
-    git clone https://gitlab.itsec.ur.de/lehrstuhl/develop/praktomat-docker.git
-    echo "Building image: $IMAGE_NAME:$FULL_TAG"
-    docker build -t "$IMAGE_NAME:$FULL_TAG" .
-    docker push "$IMAGE_NAME:$FULL_TAG"
+    - git config --global user.email "kesdogan.Technik@ur.de"
+    - git config --global user.name "GitLab CI/CD Bot"
+    - git remote set-url --push origin "https://gitlab-ci-token:${PAT}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
+    - |
+      if [ -z "$VERSION" ]; then echo "ERROR: VERSION is required"; exit 1; fi
+      BASE_TAG="${BASE_TAG:-$DEFAULT_BASE_TAG}"
+      FULL_TAG="$BASE_TAG-$VERSION"
+      echo "Building image: $IMAGE_NAME:$FULL_TAG"
+      docker build -t "$IMAGE_NAME:$FULL_TAG" .
+      docker push "$IMAGE_NAME:$FULL_TAG"
   only:
     - web
